title = "IRL Podcast: Online Life is Real Life"
email = "irlpodcast@mozilla.com"
buildFuture = true
[params]
    description = "Mozilla’s multi-award winning podcast is back! In Season 7, Bridget Todd meets tech builders who put people over profit in artificial intelligence."
