[build]
  publish = "public"
  command = "bin/build-netlify.sh"

[build.environment]
  NODE_VERSION = "v8.17.0"
  HUGO_VERSION = "0.40.2"

[context.production.environment]
  CONFIG_FILE = "prod"

[context.stage.environment]
  CONFIG_FILE = "stage"

[context.master.environment]
  CONFIG_FILE = "dev"

[context.deploy-preview.environment]
  CONFIG_FILE = "dev"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"
    Content-Security-Policy = '''
    font-src 'self' *.mozilla.net *.mozilla.org;
    img-src 'self' data: *.mozilla.net *.mozilla.org www.google-analytics.com;
    style-src 'self' 'unsafe-inline' *.mozilla.org *.mozilla.net;
    script-src 'self' 'unsafe-inline' data: *.mozilla.org *.mozilla.net www.google-analytics.com www.googletagmanager.com;
    default-src 'self' *.cdn.mozilla.net assets.mozilla.net;
    child-src 'self' player.simplecast.com embed.simplecast.com;
    form-action 'self' www.mozilla.org;
    '''

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "max-age=31536000, public, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "max-age=31536000, public, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "max-age=31536000, public"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "max-age=3600, public"

[[redirects]]
  from = "/twit"
  to = "https://2022.internethealthreport.org/?utm_medium=podcast&utm_source=twit&utm_campaign=ihr2022&utm_content=twit"

[[redirects]]
  from = "/castbox"
  to = "https://2022.internethealthreport.org/?utm_medium=podcast&utm_source=castbox&utm_campaign=ihr2022&utm_content=castbox"
